### PR TITLE
Bug 1812719: jsonnet: set cpu requests

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I honestly don't know, we are importing the jsonnet library in cluster-monitoring-operator. It seems `manifests` is unused?

**Comment by lilic** [comment]
No idea, I guess not, should we then just remove it to avoid confusion? e.g. node_exporter does not have one either https://github.com/openshift/node_exporter

Can be done in a follow up. 

/lgtm

**Comment by s-urbaniak** [comment]
ping @aditya-konarde can you approve please?

(we have to update owners btw)

**Pull request merged**
