### PR TITLE
Use dep to manage dependencies

### PR DESCRIPTION
**Pull request by wanghaoran1988**

### CODE REVIEW

**Comment by aditya-konarde** [comment]
I'm investigating if we can use go modules instead, so that we're consistent with everyone else.

**Comment by metalmatze** [comment]
@aditya-konarde Good news is, client-go was release with Go modules supported.

**Comment by aditya-konarde** [comment]
Update: I just bumped the client-go version and init the gomodule, everything works perfectly! :) 

One nit: Looks like some openshift packages will return a `410` when getting them from go proxy. To fix this I had to set go to not use the proxy on builds

**Pull request closed without merging**
