### PR TITLE
Bug 1882448: bump k8s.io/client-go dependency

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by juzhao** [comment]
tested with the PR with cluster-bot cluster `launch openshift/openshift-state-metrics#58 aws`, issue is fixed

**Comment by sdodson** [comment]
Other components have bumped to 0.18.9 in order to fix ""Too large resource version"" errors per bugs like these, should you consider bumping to that version instead or do you believe your component not to be at risk for that problem?
https://bugzilla.redhat.com/show_bug.cgi?id=1880343

**Comment by simonpasquier** [comment]
Indeed I've found [k/k #94315](https://github.com/kubernetes/kubernetes/issues/94315) which states that the [initial fix](https://github.com/kubernetes/client-go/commit/3ac0631eb9d7727b09451ed115b8b79949d7efcf) in v0.18.8 is incomplete when the Kubernetes API server version is < v1.18.6. v0.18.9 includes another [commit](https://github.com/kubernetes/client-go/commit/94230b73bde5383309f30a000f63981948057279) fixing the edge case. I can't tell for sure which version of the Kubernetes API is available in OpenShift 4.5 (seems to be v1.18.3) so in doubt, I'll update this PR.
AFAIU https://github.com/openshift/openshift-state-metrics/pull/57 is ok because 4.6 ships Kubernetes v1.19.x.

**Comment by s-urbaniak** [comment]
@sdodson thank you for the catch!

**Comment by sdodson** [comment]
/lgtm cancel
Sorry, should let someone on the team set that.

**Pull request merged**
