### PR TITLE
Bug 1818806: jsonnet: set cpu requests

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
@s-urbaniak It looks like you should open a PR for master branch first, and verified the 4.5 bug first?

**Comment by lilic** [comment]
It was already merged ;) https://github.com/openshift/openshift-state-metrics/pull/45

**Comment by s-urbaniak** [comment]
Plus, we'll most likely need an override anyways, as the changes here do not end up as payload, but only as jsonnet.

We'll have the net changes visible as PRs in cluster-monitoring-operator.

**Comment by s-urbaniak** [comment]
closing as this generates too much noise. will reopen again once 4.4 is verified.

**Comment by s-urbaniak** [comment]
(plus, there are going to be some other changes coming from a prometheus-operator backport bump, so there is most likely going to be a bigger PR coming)

**Pull request closed without merging**
